AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Portfolio Backend - Serverless API + DynamoDB

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.12
    Handler: lambda_function.lambda_handler

Parameters:
  RDSHost:
    Type: String
    Description: RDS endpoint for database connectivity
  RDSDatabase:
    Type: String
    Description: RDS database name

Resources:
  # DynamoDB Table (Products)
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductsTable
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Function
  CatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: catalog-service-v2   # Unique name
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/
      Timeout: 30
      Environment:
        Variables:
          DYNAMO_TABLE: !Ref ProductsTable
          RDS_HOST: !Ref RDSHost
          RDS_DATABASE: !Ref RDSDatabase
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        ProductsApi:
          Type: Api
          Properties:
            Path: /products
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL for the Products API
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products"

  ProductsTableName:
    Description: DynamoDB table name
    Value: !Ref ProductsTable

  LambdaFunctionName:
    Description: Deployed Lambda function name
    Value: !Ref CatalogFunction
